app.swagger_ui:
    path: /
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api.login_check:
    path: /login_check

_errors:
    resource: '@TwigBundle/Resources/config/routing/errors.xml'
    prefix: /_error


